from Map import Map
from Piece import Piece
import itertools
from matplotlib.animation import FuncAnimation
import matplotlib.pyplot as plt
import geopandas as gpd
from shapely.geometry import Polygon, LineString
import csv
import time

class Graph:
    def __init__(self, pieces: list = None, map: Map = None, piece_displacement: tuple = (0,0)):
        self.fig, self.ax = plt.subplots()
        self.ax.set_xticks([0,5,10,15])
        self.ax.set_yticks([0,5,10,15])
        self.map = map
        self.border = None
        self.total_pices_placed = None
        if self.map: 
            self.border = self.map.border
            self.total_pieces_placed = 2 + len(self.map.invisible_lines)
        self.pieces = pieces
        self.animation = None
        self.current_piece_index = 0
        #self.displace_pieces(piece_displacement)
    """
    SETS PIECES OUTSIDE OF MAP
    """

    def map_creator(self, directions: list[str], line_lengths: list[str]):
        if not line_lengths and not directions:
            return
        if len(line_lengths) != len(directions):
            IndexExror: print("amount of lines and their dircetions do not match")
            return
        def create_coordinates(directions, line_lengths):
            num_lines = len(line_lengths)
            x_coordinates = [0]
            y_coordinates = [0]
            for i in range(num_lines):
                if directions[i] == "n":
                    x_coordinates.append(x_coordinates[-1] + 0)
                    y_coordinates.append(y_coordinates[-1] + line_lengths[i])
                elif directions[i] == "e":
                    x_coordinates.append(x_coordinates[-1] + line_lengths[i])
                    y_coordinates.append(y_coordinates[-1] + 0)                 
                elif directions[i] == "s":
                    x_coordinates.append(x_coordinates[-1] + 0)
                    y_coordinates.append(y_coordinates[-1] - line_lengths[i])
                    if y_coordinates[-1] < 0:
                        y_coordinates = self.shift_graph(y_coordinates, -y_coordinates[-1])
                elif directions[i] == "w":
                    x_coordinates.append(x_coordinates[-1] - line_lengths[i])
                    y_coordinates.append(y_coordinates[-1] + 0)
                    if x_coordinates[-1] < 0:
                        x_coordinates = self.shift_graph(x_coordinates, -x_coordinates[-1])
            #x_coordinates, y_coordinates = shift_graph(x_coordinates, 2), shift_graph(y_coordinates, 2)
            
            return [(x, y) for x, y in zip(x_coordinates, y_coordinates)]
        the_map = Map(create_coordinates(directions, line_lengths))
        if self.map == None: 
            self.map = the_map
        return the_map
    

    def fill_perimater(self):
        """
        for each piece, determine whether it can fit at the try_point 0,0
        if if can, keep going with this piece, updating the try_point and testing pieces until completing the perimater
        create a new Map with the perimater filled (it would be a smaller version of the previous map)
        repeat until all pieces are filled

        
        """
        #at the end of this code I need:
            # new Map ✓
            # reduced set of Pieces
            # new try_point with ✓
            # piece adjustment metric with new try point

        #generated by chatgpt
        def on_line(point_a, point_b, check_point):
            # Calculate the cross product and dot product
            cross_product = (check_point[1] - point_a[1]) * (point_b[0] - point_a[0]) - (point_b[1] - point_a[1]) * (check_point[0] - point_a[0])
            dot_product = (check_point[0] - point_a[0]) * (point_b[0] - point_a[0]) + (check_point[1] - point_a[1]) * (point_b[1] - point_a[1])

            # Check if the points are collinear and if check_point is between point_a and point_b
            if abs(cross_product) < 0.001 and dot_product >= 0 and dot_product <= (point_b[0] - point_a[0]) * (point_b[0] - point_a[0]) + (point_b[1] - point_a[1]) * (point_b[1] - point_a[1]):
                return True

            return False

        def find_highest_coord(coordinates):
            if not coordinates: return None
            highest_coord_idx = 0
            for i in range(len(coordinates)):
                if coordinates[i][1] > coordinates[highest_coord_idx][1]:
                    highest_coord_idx = i
            return coordinates[highest_coord_idx]

        #method instuction start
        for piece in self.pieces:
            coordinates_on_perimater = []
            for orientation in piece.orientations:
                shapely_orientation = Polygon(orientation.coordinates)
                current_orientation = gpd.GeoSeries(shapely_orientation)
                current_orientation.plot(ax=self.ax)

                # UNKOWN WHY THE CODE BELOW WORKS
                if current_orientation.touches(self.border, align=True).bool():
                    
                    for i in range(len(self.map.coordinates)-1):
                        for coordinate in orientation.coordinates:
                            if on_line(self.map.coordinates[i], self.map.coordinates[i+1], coordinate):
                                coordinates_on_perimater.append(coordinate)
                else:
                    self.ax.collections[-1].remove()
            new_try_point = find_highest_coord(coordinates_on_perimater)
            new_map = self.map.eat_map(shapely_orientation)

            print(new_map)

    def animate(self, interval: int = 100):

        def update(obj):
            if len(self.ax.collections) > self.total_pieces_placed:
                self.ax.collections[self.total_pieces_placed-self.current_piece_index].remove()
            obj.plot(ax=self.ax, color='red')
        ani = FuncAnimation(self.fig, update, frames=list(itertools.chain.from_iterable([obj.get_orientations() for obj in self.pieces])), interval=interval)


    def plot_map(self):
        for line in self.map.invisible_lines:
            gpd.GeoSeries(line).plot(ax=self.ax, color='purple')
        gpd.GeoSeries(self.map.map).plot(ax = self.ax, color='blue')
        self.border = gpd.GeoSeries(self.map.border)
        self.border.plot(ax = self.ax, color='red')

    
    def display_graph(self, animate: bool = False):
        if animate:
            self.animate()
        
        plt.show(block = True)

    def displace_pieces(self, displacement):
        for piece in self.pieces:
            for orientation in piece:
                for coordinate in orientation.coordinates:
                    coordinate[0] += displacement[0]
                    coordinate[1] += displacement[1]



#        def update(obj):
#            obj.plot(ax=self.ax, color='red')
#            if len(self.ax.collections) > 2:
#                print(self.current_piece_index)
#                self.ax.collections[2-self.current_piece_index].remove()